### PR TITLE
Enabled TEGroupedMLP test.

### PR DESCRIPTION
**Pull request by wenchenvincent**

### CODE REVIEW

**Comment by gurpreet-dhami** [comment]
@wenchenvincent , @lcskrishna 
Do we want to remove the original markers e.g. "internal" ? 
At some point I wanted to run all internal tests as well and mark the failing ones for further debugging ?
I suggest to keep the original markers as it is. And add additional markers ( e.g. test_on_rocm ) for the tests like this ? 
It is easier for subsequent IFU updates as well.

**Comment by wenchenvincent** [comment]
> @wenchenvincent , @lcskrishna Do we want to remove the original markers e.g. "internal" ? At some point I wanted to run all internal tests as well and mark the failing ones for further debugging ? I suggest to keep the original markers as it is. And add additional markers ( e.g. test_on_rocm ) for the tests like this ? It is easier for subsequent IFU updates as well.

@gurpreet-dhami We should keep most of the `internal` markers. For this one, I wanted to enable the specific tests for TEGroupedMLP to make sure that we test it. I like your idea of adding additional markers instead of removing the `internal` markers. I will make the change accordingly.

**Comment by wenchenvincent** [comment]
@gurpreet-dhami @lcskrishna I refactored the test markers. Could you please review the change?

**Comment by gurpreet-dhami** [comment]
@wenchenvincent : Change looks good to me. I hope the tests are passing for you.
I saw that CI failed on another unrelated test http://ml-ci-internal.amd.com:8080/job/Megatron-LM/job/Megatron-LM/view/change-requests/job/PR-22/3/console
tests/unit_tests/transformer/test_transformer_block.py tests/unit_tests/transformer/test_transformer_block.py ........................FFFFFFFF........Fatal Python error: Aborted

I ran again. lets see how it goes.

**Comment by lcskrishna** [comment]
> @wenchenvincent : Change looks good to me. I hope the tests are passing for you. I saw that CI failed on another unrelated test http://ml-ci-internal.amd.com:8080/job/Megatron-LM/job/Megatron-LM/view/change-requests/job/PR-22/3/console tests/unit_tests/transformer/test_transformer_block.py tests/unit_tests/transformer/test_transformer_block.py ........................FFFFFFFF........Fatal Python error: Aborted
> 
> I ran again. lets see how it goes.

Seems like UTs are failing with this one in another PR as well. @gurpreet-dhami Can you take a look at this one.

**Review by lcskrishna — APPROVED** [review]

**Review by gurpreet-dhami — APPROVED** [review]

**Comment by gurpreet-dhami** [comment]
For some reason, CI is failing on your PR on transformer_block tests.

It is passing on rocm_dev branch



passing on rocm_dev - http://ml-ci-internal.amd.com:8080/job/Megatron-LM/job/Megatron-LM/job/rocm_dev/19/



failing on TEgrouped gemm PR: http://ml-ci-internal.amd.com:8080/job/Megatron-LM/job/Megatron-LM/view/change-requests/job/PR-22/4/

**Pull request merged**
